  
# my global config
global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.
    # scrape_timeout is set to the global default (10s).
  
    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'my-project'

# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
    # Scrape Prometheus itself every 5 seconds.
    - job_name: 'prometheus'
      scrape_interval: 5s
      target_groups:
        - targets: ['localhost:9090']
  
    # Scrape the Node Exporter every 5 seconds.
    - job_name: 'node'
      scrape_interval: 5s
      target_groups:
        - targets: ['node-exporter:9100']